### ISSUE TITLE
Add Button-less Option

### ISSUE THREAD

**Issue by manicslothpdx** [IBM/mac-ibm-notifications#39] opened 2021-07-30 20:40 UTC
Adding the option to have a button-less popup would be helpful for workflows that show multiple different messages to users in succession but that don't require user input. For example, when patching an application, it may make sense to show a progress bar popup, but when it's complete, instead of requiring the user to click the "Ok" button, the progress bar window would be killed and a "This patch is complete" popup would take its place.

**Comment by SMartorelli** [comment] 2021-07-30 21:14
Hi @manicslothpdx, thanks for your feedback. 
I've a couple of questions for you:
1. Do you think that a progress bar AV that at the end trigger the exit of the agent instead of showing the buttons could work? Since what you're trying to reproduce is still a background process I think that the progress bar is a good method to show it.
2. Since the second pop-up should anyway be triggered by your script, there are any differences between that one and the progress bar one with a "top_message" set to "This patch is complete" and the "Ok" button visible?

**Comment by manicslothpdx** [comment] 2021-08-02 21:31
Here are the three stages that we use:

<img width="641" alt="ac1" src="https://user-images.githubusercontent.com/16160764/127926437-6dced346-9db4-4adb-8db8-ff60cc635b27.png">

<img width="641" alt="ac2" src="https://user-images.githubusercontent.com/16160764/127926453-a0d6a762-3f4b-4df7-bae2-a345c8252db7.png">

<img width="641" alt="ac3" src="https://user-images.githubusercontent.com/16160764/127926462-d87ca04f-dceb-4383-a7b2-05a559c9f135.png">

**Comment by manicslothpdx** [comment] 2021-08-02 21:36
For question #2, the "success" message that we show is too big to fit in the "top_message" field.

I don't think I understand question #1. Right now, when the progress bar is complete, there is a brief moment when there is an "Ok" button displayed. It is mostly a cosmetic issue because we kill the window process fast so that we can sh ow the 3rd popup, but there is a moment when a user could still get confused and click the "Ok" button at the end of the progress bar. It would be "cleaner" if we didn't need to show a button at any point during the progress bar popup. We modify the tool is Xcode to do this for us so that we could test it, and our test users agreed that it was cleaner.

**Comment by SMartorelli** [comment] 2021-08-03 08:48
Hi @manicslothpdx with the first question I meant to ask you if a progress bar popup with the option to close it self automatically at the end of the process might be useful instead of it showing the buttons. We can add an additional customisation key to the progress bar accessory view (like "/auto_close"). Could this fit this feature request scope?

**Comment by manicslothpdx** [comment] 2021-08-03 19:59
In my personal opinion, in our workflow it would still look odd if a progress bar-style popup shows a button and then auto-dismisses. That's basically what we're doing now anyway with a "pkill IBM Notifier" command. It would just be nice to have the _option_ to show no button. This is what our 2nd popup looks like for a few seconds before it is killed:

<img width="641" alt="Screen Shot 2021-08-03 at 12 54 13 PM" src="https://user-images.githubusercontent.com/16160764/128078000-7687b627-b1c2-4a34-bab9-8b968df76eba.png">

**Comment by SMartorelli** [comment] 2021-08-03 20:07
Yes of course I mean it should auto dismiss and show no buttons.

**Comment by manicslothpdx** [comment] 2021-08-04 18:28
So, are you saying that if you add an "auto-close" parameter, it would also not show any button at the end of the progress bar popup? That might work. Would "auto-close" have the ability to set a timeout setting too, or would the existing timeout attribute also work?

**Comment by SMartorelli** [comment] 2021-08-04 18:38
I guess the background timeout in this case is not needed since the pop-up with the progress bar should automatically close at the end of the progress bar updates. Then the additional pop-up with the "This patch is complete" message should be anyway triggered by your script at the auto-exit of the progress bar one.

**Comment by SMartorelli** [comment] 2021-08-13 08:59
Will add a payload key for progress bar accessory view to allow the popup to automatically exit 0 at the end of the progress.

**Closed** 2021-11-03 21:23 UTC
Labels: enhancement
