### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by robertojok** [IBM/mac-ibm-notifications#93] opened 2022-06-12 12:16 UTC
**Describe the bug**
Not sure if this is a bug... I have followed the instructions on customising the app with the developer account all set up. I am using the latest Xcode 13.4.1  in Monterey.
I have performed the Archive and can see the latest archive. When I select Distribute Content, I am asked to create a folder which I do. Then I am back to the Distribute Content button again.

But I do not see the part to choose the Developer ID
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11]
 - Project version [e.g. 1.0.0]

**Additional context**

**Comment by SMartorelli** [comment] 2022-06-13 18:19
Hi @robertojok if you actually see Distribute Content instead of Distribute App you might have something wrong in your project, I suggest to re-do from scratch the [rebranding](https://github.com/IBM/mac-ibm-notifications/wiki/Rebranding-the-application) and [re-archive](https://github.com/IBM/mac-ibm-notifications/wiki/Archive,-sign-and-notarize-the-app) it. 
PS: this is not a bug of the app but an issue with your specific configuration, I'm going to close this BUG then and if you want to discuss it more please open a [Q&A Discussion](https://github.com/IBM/mac-ibm-notifications/discussions).

**Closed by SMartorelli** 2022-06-13 18:19 UTC
