### ISSUE TITLE
[BUG] Not possible to click on URL when using -always_on_top in the onboarding workflow

### ISSUE THREAD

**Issue by kryptonit1** [IBM/mac-ibm-notifications#120] opened 2022-08-30 07:11 UTC
**Describe the bug**
It is not possible to click on a URL in the onboarding UI workflow when using the **HTML accessory view** and the **-always_on_top** parameter when launching IBM Notifier. If you click on the URL frenetically it might suddenly be possible to click on the URL. When removing the **-always_on_top** parameter it works. I have seen this when adding a URL using markdown in the body key on a page as well. I have not tested if removing **-always_on_top** would solve the problem in that case as well, but I guess that it is likely. It might also be likely that this is a problem in the pop-up UI as well, but I have not tested that either.

**To Reproduce**
1. Create a page in the onboarding UI workflow that has an HTML accessory view and a URL (for example `<a href="https://www.google.com">Google</a>`).
2. Launch IBM Notifier with the **-always_on_top** parameter.
3. Tryck to click on the URL.

**Expected behavior**
The URL should be clickable.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Project version: 2.8.0

**Additional context**
N/A

**Comment by SMartorelli** [comment] 2022-08-30 07:14
Hi @kryptonit1 can you please post a sample of the json used to configure the Onboarding UI? thanks

**Comment by kryptonit1** [comment] 2022-08-30 07:36
I created a sample JSON that can be used to reproduce:

`{
    "pages":[
        {
            "title":"IT Support",
            "subtitle":"IT Support can be contacted through the following channels",
            "topIcon":"https://www.nicepng.com/png/detail/242-2426263_technical-support-tech-support-tech-support-icon.png",
            "accessoryViews":[
                                [
                                    {
                                        "type":"html",
                                        "payload":"<table style=\"width:100%;background:#ffffff;border:1px solid #000;font-family:Helvetica;font-size:14px;\"><tr style=\"background:#E6E6E6;\"><td style=\"padding: 10px;\"><b>E-mail</b></td><td style=\"padding: 10px;\">itsupport@randomcompany.com</td></tr><tr><td style=\"padding: 10px;\"><b>Phone</b></td><td style=\"padding: 10px;\">040-040123</b></td><tr style=\"background:#E6E6E6;\"><td style=\"padding: 10px;\"><b>On Site</b></td><td style=\"padding: 10px;\">Visit <a href=\"https://www.google.com\"><b>Google</b></a> for more information</tr></table>"
                                    }
                                ]
                            ]
        }
    ]
}`

Launch IBM Notifier with **-type onboarding** and without **-always_on_top** and press the URL in the window (it works). Then launch IBM Notifier with **-type onboarding** and **-always_on_top** and press the URL in the window (it is not working).

**Comment by kryptonit1** [comment] 2022-08-30 08:59
I just tried to create a URL with markdown in the body key of a page now as well and the problems exists there also. The markdown I used looks like this: `[Duck Duck Go](https://duckduckgo.com)`. In this case the problem occurs even though I am not using the **-always_on_top** parameter.

**Comment by SMartorelli** [comment] 2022-10-11 10:06
Hi @kryptonit1 can you please check if the issue is still present in the latest version of IBM Notifier. I was trying to replicate it with your suggestions but I'm not able to. I attach the script I'm using to replicate the issue.
```
#!/bin/bash

# IBM Notifier binary paths
NA_PATH="/Applications/IBM Notifier.app/Contents/MacOS/IBM Notifier"

# Variables for the popup notification for ease of customization
WINDOWTYPE="onboarding"
PAYLOAD=$(cat <<-END
{
  "pages":[
            {
              "title":"IT Support",
              "subtitle":"IT Support can be contacted through the following channels",
              "topIcon":"https://www.nicepng.com/png/detail/242-2426263_technical-support-tech-support-tech-support-icon.png",
              "body":"Click on this link --> [Duck Duck Go](https://duckduckgo.com)"
            },
            {
              "title":"IT Support",
              "subtitle":"IT Support can be contacted through the following channels",
              "topIcon":"https://www.nicepng.com/png/detail/242-2426263_technical-support-tech-support-tech-support-icon.png",
              "accessoryViews":[
                                    [
                                        {
                                          "type":"html",
                                          "payload":"<table style=\"width:100%;background:#ffffff;border:1px solid #000;font-family:Helvetica;font-size:14px;\"><tr style=\"background:#E6E6E6;\"><td style=\"padding: 10px;\"><b>E-mail</b></td><td style=\"padding: 10px;\">itsupport@randomcompany.com</td></tr><tr><td style=\"padding: 10px;\"><b>Phone</b></td><td style=\"padding: 10px;\">040-040123</b></td><tr style=\"background:#E6E6E6;\"><td style=\"padding: 10px;\"><b>On Site</b></td><td style=\"padding: 10px;\">Visit <a href=\"https://www.google.com\"><b>Google</b></a> for more information</tr></table>"
                                        }
                                    ]
                                ]
            },
            {
              "title":"IT Support",
              "subtitle":"IT Support can be contacted through the following channels",
              "topIcon":"https://www.nicepng.com/png/detail/242-2426263_technical-support-tech-support-tech-support-icon.png",
              "body":"Click on this link --> [Duck Duck Go](https://duckduckgo.com)",
              "accessoryViews":[
                                    [
                                        {
                                          "type":"html",
                                          "payload":"<table style=\"width:100%;background:#ffffff;border:1px solid #000;font-family:Helvetica;font-size:14px;\"><tr style=\"background:#E6E6E6;\"><td style=\"padding: 10px;\"><b>E-mail</b></td><td style=\"padding: 10px;\">itsupport@randomcompany.com</td></tr><tr><td style=\"padding: 10px;\"><b>Phone</b></td><td style=\"padding: 10px;\">040-040123</b></td><tr style=\"background:#E6E6E6;\"><td style=\"padding: 10px;\"><b>On Site</b></td><td style=\"padding: 10px;\">Visit <a href=\"https://www.google.com\"><b>Google</b></a> for more information</tr></table>"
                                        }
                                    ]
                                ]
            }
        ]
}
END
)

### FUNCTIONS ###

prompt_user() {
    exitvalue=$("${NA_PATH}" \
        -type "${WINDOWTYPE}" \
        -payload "${PAYLOAD}" \
        -always_on_top \
        --v )

    echo "$exitvalue"
}

### END FUNCTIONS ###

RESPONSE=$(prompt_user)
echo "$RESPONSE"

```

**Comment by kryptonit1** [comment] 2022-10-12 14:43
It seems to be working now with 2.9.1, nice! Thank you! :)

**Comment by SMartorelli** [comment] 2022-10-13 08:41
Perfect! I will close this issue than, please let us know if you experience any other bug related to this report.

**Closed by SMartorelli** 2022-10-13 08:41 UTC
Labels: bug, question
